[project]
name = 'clarity-hourbank'
description = 'HourBank - Time-based service marketplace on Stacks'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.sip010-trait]
path = 'contracts/sip010-trait.clar'
clarity_version = 3
epoch = 3.1

[contracts.time-token]
path = 'contracts/time-token.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['sip010-trait']

[contracts.user-registry]
path = 'contracts/user-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.skill-registry]
path = 'contracts/skill-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.reputation]
path = 'contracts/reputation.clar'
clarity_version = 3
epoch = 3.1

[contracts.escrow]
path = 'contracts/escrow.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['sip010-trait']

[contracts.booking-manager]
path = 'contracts/booking-manager.clar'
clarity_version = 3
epoch = 3.1

[contracts.dispute-resolver]
path = 'contracts/dispute-resolver.clar'
clarity_version = 3
epoch = 3.1

[contracts.analytics]
path = 'contracts/analytics.clar'
clarity_version = 3
epoch = 3.1

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['reputation']

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
